### ISSUE TITLE
No module named AudioConverted

### ISSUE THREAD

**Issue by chaowyc** [lamdav/AudioConverter#1]
hello, I like your package, but there is a problem after installing it according to the instructions listed in README file: No module named AudioConverted.

After checking your setup.py file, I found that there missing a key in setup dict called py_modules, which specifies the name of the module. I then moved the converter.py file out of AudioConvert folder and specified py_modules=['converter'], and install it in my local virtual env, everything is ok.

here is code snippet of setup.py :
```
setup(name='AudioConverter',
      setup_requires=['setuptools_scm'],
      description='Audio Converter CLI',
      long_description=long_description,
      long_description_content_type='text/markdown',
      author='lamdav',
      author_email='david.lam@lamdav.com',
      license='MIT',
      python_requires='>=3.5',
      py_modules=['converter'],
      entry_points={
        'console_scripts': [
            'audioconvert=converter:cli'
        ]
      },
```
This is just a simple fix, you may consider doing some fix related to the module problem in following releases.

**Comment by lamdav** [comment]
Thanks for creating an issue. 

I updated the `setup.py` file with the missing `packages` key and a call to `find_packages()`. I had also added the missing `__init__.py` for my python package 😅 . This should be fixed in version `0.0.5`. Please reinstall the latest version and see if this fixes the issue for you. 

The new version also contains a few internal clean ups but it *shouldn't* have impacted core functionalities. Feel free to reopen this issue if the problem persist.
