### ISSUE TITLE
Conflicting dependencies between requirements.txt and setup.py files

### ISSUE THREAD

**Issue by benbou8231** [lamdav/AudioConverter#7]
Hi there,

I've encountered an issue while trying to install AudioConverter v1.0.0 using pip. The requirements specified in the requirements.txt and setup.py files for AudioConverter do not match, leading to a conflict between the versions of Click required by the two files.

Specifically, requirements.txt specifies that AudioConverter requires click==8.1.3, while setup.py requires click>=7.1.2,<8.0.0. When I try to install AudioConverter using pip install AudioConverter, I get a dependency conflict error due to the mismatch between the two files.

I believe this is a bug in the package, as the requirements specified in requirements.txt and setup.py should be consistent. Could you please look into this issue and provide a fix?

Thank you for your help!

**Comment by lamdav** [comment]
Hi, I'm not able to replicate your install issue. Below are the commands I ran in a fresh virtual environment:
```
mkdir playground
cd playground
poetry init
poetry shell
pip install AudioConverter
mkdir in
mkdir out
// set up in with .aiff file
audioconvert -v convert ./in ./out -o .mp3
```

All these commands ran successfully. 

If I had to guess, it could be due to your environment and conflicting dependencies (e.g. some other dependency also depends on click). 

I have since updated to remove `requirements.txt` and `setup.py` to wholy focus on using `pyproject.toml`.
